import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Navbar from "./components/navbar/navbar";
import HeaderWrapper from "./components/header/header-wrapper";

config.autoAddCss = false;

export type Page = 'home' | 'events' | 'map' | 'my-trees' | 'report' | 'achievements' | 'admin' | 'login' | 'status-tracker' | 'profile';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <HeaderWrapper/>
                {children}
                <Navbar/>
            </body>
        </html>
    );
}